import { inngest } from '../client';
import {
  getPullRequestDiff,
  postReviewComment,
  getPullRequestMeta,
  getFileContent,
  createBranch,
  commitFile,
  createPullRequest,
  postPrComment,
} from '@/module/github/lib/github';
import { retrieveContext } from '@/module/ai/lib/rag';
import { runMultiAgentReview } from '@/module/ai/agents/graph';
import { collectActionableFindings, generateFixedFile } from '@/module/ai/agents/fixer';
import type { Prisma } from '@/lib/generated/prisma/client';
import prisma from '@/lib/db';

// Bounds on the auto-fix step to keep cost and blast radius reasonable.
const MAX_FIX_FILES = 8;
const MAX_FIXABLE_FILE_CHARS = 60000;

export const generateReview = inngest.createFunction(
  { id: "generate-review",
    concurrency: 5,
    triggers: [{event: "pr.review.requested"}],  
  },

  async ({event, step}) => {
    const {owner, repo, prNumber, userId} = event.data;

    const {diff, title, description, token} = await step.run('fetch-pr-data', async()=> {
      const account = await prisma.account.findFirst({
        where: {
          userId: userId,
          providerId: "github"
        }
      });

      if (!account?.accessToken) {
        throw new Error("No Github access token found");
      }

      const data = await getPullRequestDiff(account.accessToken, owner, repo, prNumber);

      return { ...data, token: account.accessToken}
   

    });

    const context = await step.run('retrieve-context', async()=> {
      const query = `${title}\n${description}`;

      return await retrieveContext(query, `${owner}/${repo}`);
    });

    // LangGraph orchestrates four specialist agents (best practices, security,
    // performance, documentation) in parallel plus a synthesizer node. With
    // Inngest concurrency 5, this can reach ~20 concurrent Gemini calls — lower
    // the function concurrency if Gemini rate limits become an issue.
    const { finalMarkdown, findings } = await step.run("generate-ai-review", async()=> {
      return await runMultiAgentReview({ title, description, diff, context });
    });

    await step.run('post-comment', async() => {
      await postReviewComment(token, owner, repo, prNumber, finalMarkdown);
    });

    // After the review, an auto-fix agent applies the actionable suggestions on a
    // new branch and opens a PR targeting the original PR's head branch. Best-effort:
    // any failure logs and returns null so the review still gets saved.
    const fix = await step.run('apply-fixes', async (): Promise<{ fixBranch: string; fixPrUrl: string } | null> => {
      try {
        const targets = collectActionableFindings(findings).slice(0, MAX_FIX_FILES);
        if (targets.length === 0) {
          return null;
        }

        const meta = await getPullRequestMeta(token, owner, repo, prNumber);

        if (meta.isFork) {
          await postPrComment(
            token,
            owner,
            repo,
            prNumber,
            "🤖 Auto-fix is not supported for pull requests opened from a fork yet, so no fix branch was created."
          );
          return null;
        }

        const fixBranch = `coderoad-ai-reviewer/fix/pr-${prNumber}-${Date.now()}`;
        await createBranch(token, owner, repo, fixBranch, meta.headSha);

        const fixedFiles: string[] = [];
        for (const target of targets) {
          const current = await getFileContent(token, owner, repo, target.file, meta.headRef);
          if (!current || current.content.length > MAX_FIXABLE_FILE_CHARS) {
            continue;
          }

          const updated = await generateFixedFile({
            path: target.file,
            content: current.content,
            findings: target.items,
          });

          if (!updated || updated === current.content) {
            continue;
          }

          await commitFile(token, owner, repo, {
            path: target.file,
            content: updated,
            message: `fix: apply review suggestions to ${target.file} (PR #${prNumber})`,
            branch: fixBranch,
            sha: current.sha,
          });
          fixedFiles.push(target.file);
        }

        if (fixedFiles.length === 0) {
          return null;
        }

        const body = [
          `This PR applies automated fixes for review findings on #${prNumber}.`,
          "",
          "Files updated:",
          ...fixedFiles.map((f) => `- \`${f}\``),
          "",
          "---",
          "*Generated by CodeRoad multi-agent review.*",
        ].join("\n");

        const pr = await createPullRequest(token, owner, repo, {
          title: `🤖 Auto-fix: review findings for PR #${prNumber}`,
          head: fixBranch,
          base: meta.headRef,
          body,
        });

        await postPrComment(
          token,
          owner,
          repo,
          prNumber,
          `🤖 I opened a PR with automated fixes for the review findings: ${pr.url}`
        );

        return { fixBranch, fixPrUrl: pr.url };
      } catch (error) {
        console.error("[apply-fixes] failed:", error);
        return null;
      }
    });

    await step.run('save-review', async()=> {
      const repository = await prisma.repository.findFirst({
        where: {
          owner,
          name: repo
        }
      });

      if (repository) {
        await prisma.review.create({
          data: {
            repositoryId: repository.id,
            prNumber,
            prTitle: title,
            prUrl: `https://github.com/${owner}/${repo}/pull/${prNumber}`,
            review: finalMarkdown,
            findings: findings as unknown as Prisma.InputJsonValue,
            fixBranch: fix?.fixBranch ?? null,
            fixPrUrl: fix?.fixPrUrl ?? null,
            status: "completed",
          },
        });
      }
    })

    return {success: true}
  }
)