import { inngest } from '../client';
import {
  getRepoFileContents,
  getDefaultBranch,
  getFileContent,
  createBranch,
  commitFile,
  createPullRequest,
} from '@/module/github/lib/github';
import { runSecurityScan, collectCriticalFixTargets } from '@/module/ai/agents/security-scan';
import { generateFixedFile } from '@/module/ai/agents/fixer';
import type { Prisma } from '@/lib/generated/prisma/client';
import prisma from '@/lib/db';

// Bounds on the critical auto-fix step to keep cost and blast radius reasonable.
const MAX_FIX_FILES = 8;
const MAX_FIXABLE_FILE_CHARS = 60000;

export const scanRepoSecurity = inngest.createFunction(
  {
    id: "scan-repo-security",
    concurrency: 3,
    triggers: [{ event: "repository.security_scan.requested" }],
    // If the run fails permanently, flag the scan so the UI doesn't hang on "running".
    onFailure: async ({ event }) => {
      const original = event.data.event.data as { scanId?: string };
      if (original?.scanId) {
        await prisma.securityScan.update({
          where: { id: original.scanId },
          data: { status: "failed", error: event.data.error?.message ?? "Scan failed" },
        });
      }
    },
  },

  async ({ event, step }) => {
    const { scanId, owner, repo, userId } = event.data;

    await step.run('mark-running', async () => {
      await prisma.securityScan.update({
        where: { id: scanId },
        data: { status: "running" },
      });
    });

    const { files, token } = await step.run('fetch-files', async () => {
      const account = await prisma.account.findFirst({
        where: { userId, providerId: "github" },
      });

      if (!account?.accessToken) {
        throw new Error("No Github access token found");
      }

      const repoFiles = await getRepoFileContents(account.accessToken, owner, repo);
      return { files: repoFiles, token: account.accessToken };
    });

    const { findings, report, counts } = await step.run('run-scan', async () => {
      return await runSecurityScan({ repoId: `${owner}/${repo}`, files });
    });

    // Best-effort: open a PR with fixes for the critical findings. Any failure
    // logs and returns null so the scan report is still saved.
    const fix = await step.run(
      'apply-critical-fixes',
      async (): Promise<{ fixBranch: string; fixPrUrl: string } | null> => {
        try {
          const targets = collectCriticalFixTargets(findings).slice(0, MAX_FIX_FILES);
          if (targets.length === 0) {
            return null;
          }

          const base = await getDefaultBranch(token, owner, repo);
          const fixBranch = `codehorse/security-fix/${scanId}`;
          await createBranch(token, owner, repo, fixBranch, base.sha);

          const fixedFiles: string[] = [];
          for (const target of targets) {
            const current = await getFileContent(token, owner, repo, target.file, base.branch);
            if (!current || current.content.length > MAX_FIXABLE_FILE_CHARS) {
              continue;
            }

            const updated = await generateFixedFile({
              path: target.file,
              content: current.content,
              findings: target.items,
            });

            if (!updated || updated === current.content) {
              continue;
            }

            await commitFile(token, owner, repo, {
              path: target.file,
              content: updated,
              message: `fix(security): apply fixes to ${target.file}`,
              branch: fixBranch,
              sha: current.sha,
            });
            fixedFiles.push(target.file);
          }

          if (fixedFiles.length === 0) {
            return null;
          }

          const body = [
            `This PR applies automated fixes for **critical** security findings detected by the CodeRoad security scan.`,
            "",
            "Files updated:",
            ...fixedFiles.map((f) => `- \`${f}\``),
            "",
            "---",
            "*Generated by CodeRoad security scan.*",
          ].join("\n");

          const pr = await createPullRequest(token, owner, repo, {
            title: `🔒 Security fixes for ${owner}/${repo}`,
            head: fixBranch,
            base: base.branch,
            body,
          });

          return { fixBranch, fixPrUrl: pr.url };
        } catch (error) {
          console.error("[security-scan apply-critical-fixes] failed:", error);
          return null;
        }
      }
    );

    await step.run('save-scan', async () => {
      await prisma.securityScan.update({
        where: { id: scanId },
        data: {
          status: "completed",
          report,
          findings: findings as unknown as Prisma.InputJsonValue,
          criticalCount: counts.critical,
          highCount: counts.high,
          totalCount: counts.total,
          fixBranch: fix?.fixBranch ?? null,
          fixPrUrl: fix?.fixPrUrl ?? null,
        },
      });
    });

    return { success: true, findings: counts.total };
  }
);
